// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'Get-Started/intro',
      label: 'Onion Omega2 Documentation',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'Get-Started/First-Time',
        'Get-Started/First-Time-Command-Line',
        'Get-Started/Troubleshooting',
        'Get-Started/Using-the-Console/Intro',
        'Get-Started/Using-the-Command-Line/Intro',
        'Get-Started/Finding-the-Omega-Name',
        'Get-Started/First-Time-Components/Hardware-Prep-No-Dock',
        'Get-Started/IP-addr-collisions',
      ],
    },
    {
      type: 'category',
      label: 'Hardware Overview',
      items: [
        'Hardware-Overview/Devices/Omega2',
        'Hardware-Overview/Devices/Omega2P',
        'Hardware-Overview/Devices/Omega2S',
        'Hardware-Overview/Devices/Omega2-Pro',
        'Hardware-Overview/Devices/Omega2-Dash',
        'Hardware-Overview/Devices/Omega2-LTE',
        'Hardware-Overview/Docks/Expansion-Dock',
        'Hardware-Overview/Docks/Power-Dock',
        'Hardware-Overview/Docks/Power-Dock-2',
        'Hardware-Overview/Docks/Mini-Dock',
        'Hardware-Overview/Docks/Arduino-Dock-2',
        'Hardware-Overview/Docks/Breadboard-Dock',
        'Hardware-Overview/Expansions/Relay-Expansion',
        'Hardware-Overview/Expansions/PWM-Expansion',
        'Hardware-Overview/Expansions/OLED-Expansion',
        'Hardware-Overview/Expansions/Ethernet-Expansion',
        'Hardware-Overview/Expansions/Rfid-Nfc-Expansion',
        'Hardware-Overview/Expansions/ADC-Expansion',
        'Hardware-Overview/Expansions/Proto-Expansion',
        'Hardware-Overview/Expansions/GPS-Expansion',
        'Hardware-Overview/Docks/Compatibility-Table',
      ],
    },
    {
      type: 'category',
      label: 'Using the Omega',
      items: [
        'Doing-Stuff/Using-GPIOs',
        'Doing-Stuff/The-Omega-LED',
        'Doing-Stuff/USB/USB-Storage',
        'Doing-Stuff/Using-MicroSD',
        {
          type: 'link',
          label: 'Installing the Console',
          href: '/omega2-legacy/Doing-Stuff/Using-the-Console/Installing-the-Console',
        },
        'Doing-Stuff/Transferring-Files',
        'Doing-Stuff/Using-the-Omega/Cloud-Platforms',
        'Doing-Stuff/Using-the-Omega/Reboot',
        {
          type: 'link',
          label: 'Updating the Omega',
          href: '/omega2-legacy/Get-Started/Using-the-Command-Line/Updating-the-Omega',
        },
        'Doing-Stuff/Using-the-Omega/Factory-Reset',
        'Doing-Stuff/USB/Playing-Audio',
        'Doing-Stuff/Arduino-Dock/Flashing-the-Microcontroller',
        'Doing-Stuff/Pin-Multiplexing',
        'Doing-Stuff/Generating-PWM-Signals',
        'Doing-Stuff/Peripherals/i2c',
        'Doing-Stuff/Peripherals/spi',
        'Doing-Stuff/Peripherals/uart1',
        'Doing-Stuff/Peripherals/one-wire',
      ],
    },
    {
      type: 'category',
      label: 'Software',
      items: [
        'Doing-Stuff/Installing-Software/Using-opkg',
        'Doing-Stuff/Installing-Software/Installing-and-Using-Git',
        'Doing-Stuff/Installing-Software/Installing-and-Using-Python',
        'Doing-Stuff/Installing-Software/Installing-and-Using-NodeJS',
        'Doing-Stuff/Installing-Software/Installing-and-Using-PHP',
        'Doing-Stuff/Installing-Software/node-red',
      ],
    },
    {
      type: 'category',
      label: 'Automation',
      items: [
        'Doing-Stuff/Automation/Running-a-command-on-boot',
        'Doing-Stuff/Automation/Running-a-command-on-a-schedule',
      ],
    },
    {
      type: 'category',
      label: 'The Omega and Connectivity',
      items: [
        'Doing-Stuff/Connectivity/The-Omega-and-Wireless',
        'Doing-Stuff/Connectivity/Finding-the-Omegas-IP-Address',
        'Doing-Stuff/Connectivity/ethernet-port',
        {
          type: 'link',
          label: 'Using the Ethernet Expansion',
          href: '/omega2-legacy/Doing-Stuff/Connectivity/ethernet-expansion',
        },
        {
          type: 'category',
          label: 'Networking with the Omega',
          items: [
            'Doing-Stuff/The-Omega-and-Networking/Omega-Router',
            'Doing-Stuff/The-Omega-and-Networking/Wifi-Range-Extender',
            'Doing-Stuff/The-Omega-and-Networking/Ethernet-Bridge',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Using the Omega Expansions',
      items: [
        'Doing-Stuff/Expansions/Using-the-Relay-Expansion',
        'Doing-Stuff/Expansions/Using-the-PWM-Expansion',
        'Doing-Stuff/Expansions/Using-the-OLED-Expansion',
        {
          type: 'link',
          label: 'Using the Ethernet Expansion',
          href: '/omega2-legacy/Doing-Stuff/Connectivity/ethernet-expansion',
        },
        'Doing-Stuff/Expansions/Using-the-GPS-Expansion',
        'Doing-Stuff/Expansions/Using-the-RFID-NFC-Expansion',
        'Doing-Stuff/Expansions/Using-the-ADC-Expansion',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'Doing-Stuff/USB/Extend-the-Omegas-memory',
        'Doing-Stuff/Advanced/Manual-Firmware-Installation',
        'Doing-Stuff/Advanced/MAC-Address',
        'Doing-Stuff/Advanced/Boot-from-External-Storage',
        'Doing-Stuff/Advanced/C-Compiler-on-Omega',
        'Doing-Stuff/Advanced/Cross-Compile',
        {
          type: 'doc',
          id: 'Doing-Stuff/Advanced/Bootloader-Flashing-Web-Recovery',
          label: 'The Bootloader',
        },
        {
          type: 'doc',
          id: 'Doing-Stuff/Advanced/Firmware-Flashing-Web-Recovery',
          label: 'Firmware Flashing With Web Recovery Mode',
        },
        'Doing-Stuff/Advanced/Firmware-Flashing-from-USB-Storage',
        {
          type: 'link',
          label: 'Updating the Bootloader',
          href: '/omega2-legacy/Doing-Stuff/Advanced/Bootloader-Flashing-Web-Recovery',
        },
      ],
    },
    {
      type: 'category',
      label: 'The Command Line',
      items: [
        'Get-Started/Using-the-Command-Line/connecting',
        'Get-Started/Using-the-Command-Line/Connecting-to-WiFi-Networks',
        'Get-Started/Using-the-Command-Line/Adjusting-the-AP-Network',
        'Get-Started/Using-the-Command-Line/Updating-the-Omega',
        'Get-Started/Using-the-Command-Line/Developing-Using-the-Command-Line',
      ],
    },
    {
      type: 'category',
      label: 'The Console',
      items: [
        'Get-Started/Using-the-Console/Installing-the-Console',
        'Get-Started/Using-the-Console/Accessing-the-Console',
        'Get-Started/Using-the-Console/Connecting-to-Wifi-Networks',
        'Get-Started/Using-the-Console/Adjusting-the-Ap-Network',
        'Get-Started/Using-the-Console/Updating',
        'Get-Started/Using-the-Console/Installing-Apps',
        'Get-Started/Using-the-Console/Developing-using-the-console',
      ],
    },
    {
      type: 'category',
      label: 'Linux Introduction',
      items: [
        'Linux-Introduction/linux-for-omega-beginners',
        'Linux-Introduction/the-command-line-interface',
        'Linux-Introduction/exploring-the-file-system',
        'Linux-Introduction/redirection',
        'Linux-Introduction/shell-scripting',
        'Linux-Introduction/ownership-and-permissions',
      ],
    },
    'Doing-Stuff/Intro-to-UCI',
    {
      type: 'category',
      label: 'Firmware Reference',
      items: [
        'Firmware-Reference/known-firmware-issues',
        'Firmware-Reference/firmware-changelog',
      ],
    },
    {
      type: 'category',
      label: 'Software Reference',
      items: [
        'Reference/Software/c-programming-language',
        'Reference/Software/python-programming-language',
        'Reference/Libraries/I2C-C-Library',
        'Reference/Libraries/PWM-Expansion-C-Library',
        'Reference/Libraries/Relay-Expansion-C-Library',
        'Reference/Libraries/OLED-Expansion-C-Library',
        'Reference/Libraries/I2C-Python-Module',
        'Reference/Libraries/SPI-Python-Module',
        'Reference/Libraries/GPIO-Python-Module',
        'Reference/Libraries/PWM-Expansion-Python-Module',
        'Reference/Libraries/Relay-Expansion-Python-Module',
        'Reference/Libraries/OLED-Expansion-Python-Module',
      ],
    },
  ],
};

module.exports = sidebars;
